name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  typecheck_lint_test:
    name: TypeScript · Lint · Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npm run typecheck --if-present || npx tsc --noEmit

      - name: Lint & Format
        run: |
          if npm run -s biome --help > /dev/null 2>&1 || npx -y @biomejs/biome --version > /dev/null 2>&1; then
            npx @biomejs/biome lint .
            npx @biomejs/biome format . --check
          else
            npm run lint --if-present
            npm run format:check --if-present
          fi

      - name: Unit Tests
        run: npm test --if-present -- --run

  npm_security:
    name: NPM Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: NPM Audit (High & Critical)
        run: npm audit --audit-level=high
        continue-on-error: true
    
      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Check for known vulnerabilities
        run: |
          if npm audit --audit-level=critical --json | jq -e '.metadata.vulnerabilities.critical > 0' > /dev/null 2>&1; then
            echo "❌ Critical vulnerabilities found!"
            npm audit --audit-level=critical
            exit 1
          else
            echo "✅ No critical vulnerabilities"
          fi

  openapi_types:
    name: OpenAPI Types
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && hashFiles('openapi.yaml', 'openapi.yml') != '' }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Generate OpenAPI types
        run: |
          npx -y openapi-typescript ./openapi.yaml -o src/lib/openapi.types.ts || \
          npx -y openapi-typescript ./openapi.yml -o src/lib/openapi.types.ts

      - name: Verify types compile
        run: npx tsc --noEmit

  supabase_types:
    name: Supabase Types
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Check if Supabase is configured
        id: check_supabase
        run: |
          if [ -n "$SUPABASE_PROJECT_ID" ] && [ -n "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "configured=true" >> $GITHUB_OUTPUT
          else
            echo "configured=false" >> $GITHUB_OUTPUT
            echo "⚠️ Supabase credentials not configured, skipping type generation"
          fi

      - name: Install Supabase CLI
        if: steps.check_supabase.outputs.configured == 'true'
        run: npm i -g supabase

      - name: Generate database types
        if: steps.check_supabase.outputs.configured == 'true'
        run: supabase gen types typescript --project-id "$SUPABASE_PROJECT_ID" > src/lib/database.types.ts

      - name: Verify types compile
        if: steps.check_supabase.outputs.configured == 'true'
        run: npx tsc --noEmit

  ai_pr_review:
    name: AI Code Review
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write
    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      AI_MODEL: ${{ vars.AI_MODEL || 'anthropic/claude-3.5-sonnet' }}
      AI_REVIEW_ENABLED: ${{ vars.AI_REVIEW_ENABLED }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if AI review is enabled
        id: check_ai
        run: |
          if [ "$AI_REVIEW_ENABLED" = "true" ] && [ -n "$OPENROUTER_API_KEY" ]; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
            echo "⚠️ AI review not enabled or API key missing"
          fi

      - name: Setup Node
        if: steps.check_ai.outputs.enabled == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install GitHub CLI
        if: steps.check_ai.outputs.enabled == 'true'
        run: sudo apt-get install gh -y


      - name: Get PR diff
        if: steps.check_ai.outputs.enabled == 'true'
        id: diff
        shell: bash
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git fetch origin ${{ github.head_ref }} --depth=1
          
          if ! git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }} --quiet; then
            echo '```diff' > /tmp/diff.txt
            git diff --unified=3 origin/${{ github.base_ref }}...origin/${{ github.head_ref }} \
              | head -c 100000 >> /tmp/diff.txt
            echo -e "\n\n...[diff truncated]...\n```" >> /tmp/diff.txt
            echo "has_diff=true" >> $GITHUB_OUTPUT
          else
            echo "has_diff=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Prepare review prompt
        if: steps.check_ai.outputs.enabled == 'true' && steps.diff.outputs.has_diff == 'true'
        run: |
          echo "You are an expert TypeScript/React code reviewer." > /tmp/prompt.txt
          echo "" >> /tmp/prompt.txt
          if [ -f ".ai/rules.md" ]; then
            cat .ai/rules.md >> /tmp/prompt.txt
          else
            cat << 'EOF' >> /tmp/prompt.txt
Review this code for:
- TypeScript errors and type safety issues
- React anti-patterns and hooks violations
- Accessibility (a11y) issues
- shadcn/ui component usage
- Supabase RLS policy violations
- Security vulnerabilities
- Performance concerns

Provide specific, actionable suggestions with code examples.
EOF
          fi

      - name: Run AI review via OpenRouter
        if: steps.check_ai.outputs.enabled == 'true' && steps.diff.outputs.has_diff == 'true'
        run: |
          node - <<'NODE'
const fs = require('fs');

const system = fs.readFileSync('/tmp/prompt.txt', 'utf8');
const diff = fs.readFileSync('/tmp/diff.txt', 'utf8');
const model = process.env.AI_MODEL || 'anthropic/claude-3.5-sonnet';

async function main() {
  console.log(`🤖 Using AI model: ${model}`);
  
  const body = JSON.stringify({
    model: model,
    messages: [
      { role: "system", content: system },
      { role: "user", content: `Review this PR diff:\n\n${diff}` }
    ],
    temperature: 0.2
  });

  const resp = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
      "HTTP-Referer": "https://github.com",
      "X-Title": "GitHub Actions CI"
    },
    body
  });

  if (!resp.ok) {
    const txt = await resp.text();
    throw new Error(`OpenRouter error: ${txt}`);
  }

  const json = await resp.json();
  const review = json.choices?.[0]?.message?.content || "No review generated.";

  const eventData = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
  const prNumber = eventData.pull_request?.number;
  
  if (!prNumber) {
    console.log("⚠️ No PR number found, skipping comment");
    return;
  }

  const { execSync } = require('child_process');
  const reviewWithHeader = `## 🤖 AI Code Review (${model})\n\n${review}`;
  
  execSync(`gh pr comment ${prNumber} --body-file -`, { 
    input: reviewWithHeader,
    stdio: ['pipe', 'inherit', 'inherit']
  });
  
  console.log("✅ AI review posted successfully");
}

main().catch(err => {
  console.error("❌ AI review failed:", err.message);
  process.exit(0);
});
NODE
